---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1wzspm9sh5qhsewgvj9xnta35ppzjy3mtv796kkj8palqpza3tgjqmm505g"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1wzspm9sh5qhsewgvj9xnta35ppzjy3mtv796kkj8palqpza3tgjqmm505g"
