---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 15m
  chart:
    spec:
      chart: longhorn
      version: 1.7.1
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    # cleanupOnFail: true
    remediation:
      retries: 3
  values:
    defaultSettings:
      # backupTarget: "nfs://${NAS0_IP}:/volume1/longhorn-backups"
      createDefaultDiskLabeledNodes: true
      defaultReplicaCount: 3
      deletingConfirmationFlag: true # TODO: Disable this when all works
    # longhornUI:
    #   replicas: 3
    ingress:
      enabled: true
      ingressClassName: internal
      host: longhorn.${SECRET_DOMAIN}
      path: /
      # annotations:
      #   external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_PUBLIC_DOMAIN}"
      #   external-dns/is-public: "true"

