apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:OrFBNirhWTd8UNw=,iv:N1SPcS3fdPW3z3DO/ZweE6oJ7NV8tdxQDzDZZyYD/zw=,tag:xeoj3yFhqrmttIda6MpLzQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:C1L/IbAG8qlBmQsNOFc=,iv:48bE0R4mNlyD5Jje5MXks1xFgCbXV/4Yz9HiudLzkv4=,tag:8A/c3PNB8RlNMJPactCJ0w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:92pvNBLbHQ1Z/b3JGD75/ES9Rrmc0vkSEtUxmeGl1XAeqAI9,iv:nSe7YdYy89m+FfA3XikZIjaMpxopVwwL/wwhnRUqFF8=,tag:ZahqgIMnG3uLv7qt9cXP0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wzspm9sh5qhsewgvj9xnta35ppzjy3mtv796kkj8palqpza3tgjqmm505g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUS9uTUoxYmZMTHVCSkpV
            aENKK3Y0VWVwTDBXcDNxcGZtZXB3emVZbURJCjRjc3ZlUlJUSGoxcXEyL2VZT0ZO
            WU4rN0k5a2pweEFHc2hrWGFHbU5wOHMKLS0tIHdaSno0T0hsSllqZWlvZWsvQWZ4
            cDR6Q2Z0dEVMRjNUSzk4aldDUDRtTEkKD4Z1+WnwrFSFE3KyQN5dU7Bj6qkcgFqI
            qcDbXgfPSHBtxg8SZSyun7s3dSb7v0OjxD1Z2+FztqoEBtj+MWOLrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-09T08:37:07Z"
    mac: ENC[AES256_GCM,data:GE7eE68s273jEBO42B1UwGZ4wiCigWbNACTw3evX45Y4p3WkzesguelUHzPTPx3QXr4Xy6o4pUKz/EaPezNeIQTcBI9XmAqmYqmSZLiNxDwJgNY+WnXxZFvfjfUyeHdPHGI9OcfdPNwd/Na2stFGesQ4fxLZnKVKb9VP8AGEAcw=,iv:hBJBWcqjvqp3KEGtACRlV4EL0Wqo7wYbynZC1qYULNc=,tag:XQCg6cgg8wTYqqMK5MHoUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
