apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:GAGEA24fMbmkz6TT6bPaYrcpGURgp/jRUIH055seiN40+vRLyN+lDgMLhhvvqMHyKo8ZOiyVLOPGfLeu+dILcPQOGJwTvHo+n1ysuhTB7tVt,iv:7DsogQmGUxehrFqSrBjNYVxmwLasKlFrr9mqUo6RMS0=,tag:uRZK00RI6KqAOGCYuUXyMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wzspm9sh5qhsewgvj9xnta35ppzjy3mtv796kkj8palqpza3tgjqmm505g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVDlzUWRIdGlPTVR4UFky
            ZnFtdEhSbTlsQXBGd0NNdG9WVWVYcHJPdTIwCmhmZVk0NUdKU2hwMGpDY2ZzN1lt
            WVZmb09nM3pLbGh4SXBMcEdTTThFa2cKLS0tIDI4YnN3Q1ZTc0lLc0F1QzczTU10
            ZURrZ1FLcHVCVG95VWwzNTkxWUFvN00KnCN6Ug5xuaLszCxGINSK21maHyLTra3B
            loWRUclR58GobdldMgO65EIx/mq/r6tLFb6DGu9kVuq8LVfDFgN3ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-08T18:44:53Z"
    mac: ENC[AES256_GCM,data:WRAI1E9XiAmM7gV4EVSD8JwCErEe2c/k6chpAiQMkex/le9BkEVdgXKUEfHVbYY3c7fTYeEMISQ8SzhJ1rM1xvHSdWq4IRikjNR8t17xYJH/9hH9BMIL7BKAt+rtgo2w08fO6nyfuxUtTdGf0naDXxO9loTA+lgVe4JYQbbpkCs=,iv:C/jRSL0fM8eyOq0FS7aGsCgUHMkoGwbbFwspK0zw/cU=,tag:yzf9+lQHm7dQCnhpzopxdw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
