apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:jaCNSG79TaRQ3qg=,iv:jVdUTn4+EA1DFY38pb/WE6t7ytcYYLBBYDZu840OfJM=,tag:GYrK3MsvdlG6mcyBYN7t7g==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:FhwKlHKUL4eRYxnBACo=,iv:Q9vDmu8GXRvMgwJy8kwEzjCEOr6Cemo3kMDhs44E5gk=,tag:Ug+cAnGHTfAzHbDmwBWJxw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Wlgux6Oak/LCt1uZhfW2ZBREDH+XSnFcwmpES4Uov86RF0de,iv:2JzG8codMsr/ZJdgwvjw5sPieHIc4VAb1sLm+GT2tck=,tag:mPW3Z49SpcbZsnzEpptwDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wzspm9sh5qhsewgvj9xnta35ppzjy3mtv796kkj8palqpza3tgjqmm505g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQV2FQdGkwRGFRaFR2NDB2
            RGJHRWplajdlVitqS2NiSG40aWNvQ3J5QmdVCnhKVEdhZm14L0Y5Sm5kelB3VkVT
            dHdPeUthUCtGaG5kT1lTZW9mWVdiYVEKLS0tIGlIakU5VGQ4WjhLaU5rOTg3M0ZB
            UmhZNXZGUjU3VTNTNDVFWkkzYkJzTVEKSAMl+eNjC8v/2vtYERvp0ieJvBKFxWfG
            FykOd3IO73A1ZWfxAgTpoYZOOz8RLsmNAgMoe+4uFmRdXCV4knIM+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-09T09:29:59Z"
    mac: ENC[AES256_GCM,data:2a9QvtMqcU4JhhRXVhsoJ1ZkGlTQW1mPRaw32UoDo/foTGPsHyl/l4GbyEpdWRknEt6uYLg+uwcftqUAtoMxrczBbdDfmJTgHBN1mCNgqTVFh6y4jHtgXJX3+n7O8aVcJMQ7blOn+Krqs++DbODz9k1B+bQWTaxsIRgcnnAwi7s=,iv:BcjugUzcQAAAAvMx23BEXBE/Z8901K3wVevsOwiIed8=,tag:VrCzTVFKyHc808f7U44KKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
