apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:WbnTkefzlZ4LX+9g722qm+okhhcg74m3rSszTXGelIU=,iv:3mAbvnUT4ykWIZe2o6xaiSjGe/5vij4khXVt/9iFzTM=,tag:8m+7Minarco76BC4R/AqPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wzspm9sh5qhsewgvj9xnta35ppzjy3mtv796kkj8palqpza3tgjqmm505g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeEo0NmI2ZTFVbVZVMXJG
            TCtPL1NQS2g4bTBjWWE0Vmk4LzRzQlVYZVRzCkxjUmp6WTNkMFRHYjFleWtITVh0
            NEUzNG9CdGJPM3ZsV2xGdDlCRGZDdjgKLS0tIGZCc3lqMkh4TlJEeGY5dmc5WFFv
            WGlHRGptVW9GUXRFVlpaRi9lSU81MGcK2cRlNGm6wPLVss5+jDGLmb0NpyBjTtHO
            gN2IoJkJ5gX+2B6rBi6PH/89bJmFCZfYXm1WMVuGcEUhKKtw5vfwSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-08T19:15:05Z"
    mac: ENC[AES256_GCM,data:PFqrO4Asy+d3cROsaMo/MIofzKnbX7CgNjhuNRbejTWW4KpuuuUqZlfLZ6LxfaFQ+XDnh3v7tSFBxizLtNlUG/4szusZBYrpdAsjYDeDSK0qSwYLLRke8BX/jx8owiEpo/D0KNTD2RqvNgWraSjXUGiwNu9eLBihgH/vcpCJ2+I=,iv:G085GROezNxUcXOU2P6EFAYi0ZWZHPhiIwQy00MhfOI=,tag:981AjrmWXQclJ2zfxc5+Bg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
